[package]
name = "binaryen-ir"
version = "0.1.0"
edition = "2021"

[dependencies]
binaryen-core = { path = "../binaryen-core" }
bitflags = "2.4"
bumpalo = { version = "3.19.1", features = ["collections"] }
wat = "1.217"
wasmprinter = "0.217"
